/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import models.Livro;
import service.ServiceLivro;


/**
 *
 * @author Dan
 */
public class CadastroLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        fValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fTitulo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fAutor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fEditora = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fIsbn = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        fEdicao = new javax.swing.JTextField();
        comboIdioma = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fieldValor = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        fEstoque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        fAltura = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        fLargura = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        fPeso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fNumeroPaginas = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        fValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fValorKeyTyped(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobre o Livro"));

        jLabel10.setText("Titulo *");

        fTitulo.setColumns(2);
        fTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fTituloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fTituloKeyTyped(evt);
            }
        });

        jLabel13.setText("Autor *");

        fAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fAutorKeyTyped(evt);
            }
        });

        jLabel14.setText("Editora *");

        jLabel12.setText("ISBN *");

        fIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fIsbnActionPerformed(evt);
            }
        });
        fIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fIsbnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fIsbnKeyTyped(evt);
            }
        });

        jLabel27.setText("Gênero");

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drama", "Romance", "Aventura", "Sci-Fi" }));

        jLabel32.setText("Idioma");

        jLabel33.setText("Edição *");

        fEdicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fEdicaoKeyTyped(evt);
            }
        });

        comboIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Ingles" }));

        jLabel1.setText("Valor *");

        try {
            fieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });
        fieldValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldValorKeyTyped(evt);
            }
        });

        jLabel3.setText("Estoque *");

        fEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fEstoqueKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(fIsbn)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fAutor)
                            .addComponent(fTitulo))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboIdioma, 0, 139, Short.MAX_VALUE)
                        .addComponent(comboGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(fAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(comboIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel33)
                        .addComponent(fEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(fEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cadastro de Livros");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Características Físicas"));

        jLabel28.setText("Altura");

        fAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fAlturaKeyTyped(evt);
            }
        });

        jLabel29.setText("Largura");

        fLargura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fLarguraKeyTyped(evt);
            }
        });

        jLabel31.setText("Peso");

        fPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fPesoKeyTyped(evt);
            }
        });

        jLabel11.setText("Número de Páginas");

        fNumeroPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNumeroPaginasKeyTyped(evt);
            }
        });

        jLabel30.setText("Cm");

        jLabel34.setText("Cm");

        jLabel35.setText("g");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fLargura, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(fAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(fNumeroPaginas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(fAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(fNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(fLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(fPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(26, 26, 26))
        );

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        Livro livro = new Livro();
        
        livro.setTitulo(fTitulo.getText());
        livro.setEditora(fEditora.getText());
        livro.setAutor(fAutor.getText());
        livro.setGenero(comboGenero.getSelectedItem().toString());  
        livro.setIdioma(comboIdioma.getSelectedItem().toString());
        livro.setLargura(fLargura.getText());
        livro.setPeso(fPeso.getText());
        livro.setEdicao(fEdicao.getText());
        livro.setAltura(fAltura.getText());
        livro.setIsbn(fIsbn.getText());
        livro.setEstoque(Integer.parseInt(fEstoque.getText()));
        livro.setValor(Float.parseFloat(fieldValor.getText()));
        
        try{
            livro.setNumeroPaginas(Integer.parseInt(fNumeroPaginas.getText())); 
        }catch(Exception e){
            
        }      
        
        try{
            ServiceLivro.cadastrarLivro(livro);
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),"Erro", 
            JOptionPane.ERROR_MESSAGE);
            return;
            
        
        }
        
        JOptionPane.showMessageDialog(this, "Livro Cadastrado");
        
        fEstoque.setText("");
        fTitulo.setText("");
        fEditora.setText("");
        fAutor.setText("");
        fEdicao.setText("");
        fIsbn.setText("");
        comboGenero.setSelectedIndex(0);
        fPeso.setText("");
        fAltura.setText("");
        fNumeroPaginas.setText("");
        fLargura.setText("");
        fieldValor.setText("");
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void fTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTituloKeyTyped
        if(fTitulo.getText().length() > 50){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 50 Caracteres");
        }
    }//GEN-LAST:event_fTituloKeyTyped

    private void fTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTituloKeyReleased

    }//GEN-LAST:event_fTituloKeyReleased

    private void fIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fIsbnActionPerformed

    private void fIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fIsbnKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789-";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fIsbn.getText().length() > 10){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 10 Numeros");
        }
    }//GEN-LAST:event_fIsbnKeyTyped

    private void fIsbnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fIsbnKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fIsbnKeyReleased

    private void fAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAutorKeyTyped
        String permitidos = " abcdefghijklmnopqrstuwyvxz".toUpperCase();
        Character ch = evt.getKeyChar();
        if(!permitidos.contains(ch.toString().toUpperCase())){
            evt.consume();
        }
        
        if(fAutor.getText().length() > 50){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 50 Caracteres");
        }
    }//GEN-LAST:event_fAutorKeyTyped

    private void fEdicaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fEdicaoKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fEdicao.getText().length() == 2){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 2 Numeros");
        }
    }//GEN-LAST:event_fEdicaoKeyTyped

    private void fValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fValorKeyTyped
    }//GEN-LAST:event_fValorKeyTyped

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValorActionPerformed

    private void fieldValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldValorKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789.,";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        } else if(fieldValor.getText().length() == 10){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Excede o valor Maximo permitido");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValorKeyTyped

    private void fNumeroPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNumeroPaginasKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fNumeroPaginas.getText().length() == 4){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 4 Numeros");
        }
    }//GEN-LAST:event_fNumeroPaginasKeyTyped

    private void fAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAlturaKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fAltura.getText().length() == 4){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 4 Numeros");
        }
    }//GEN-LAST:event_fAlturaKeyTyped

    private void fLarguraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fLarguraKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fLargura.getText().length() == 4){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 4 Numeros");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_fLarguraKeyTyped

    private void fPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fPesoKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fPeso.getText().length() == 4){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 4 Numeros");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_fPesoKeyTyped

    private void fEstoqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fEstoqueKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fEstoque.getText().length() == 4){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 4 Numeros");
        }
    }//GEN-LAST:event_fEstoqueKeyTyped

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboIdioma;
    private javax.swing.JTextField fAltura;
    private javax.swing.JTextField fAutor;
    private javax.swing.JTextField fEdicao;
    private javax.swing.JTextField fEditora;
    private javax.swing.JTextField fEstoque;
    private javax.swing.JTextField fIsbn;
    private javax.swing.JTextField fLargura;
    private javax.swing.JTextField fNumeroPaginas;
    private javax.swing.JTextField fPeso;
    private javax.swing.JTextField fTitulo;
    private javax.swing.JTextField fValor;
    private javax.swing.JFormattedTextField fieldValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
