/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.DaoCliente;
import models.Cliente;
/**
 *
 * @author danilo.martinez
 */
public class PesquisaCliente extends javax.swing.JInternalFrame {
    private TelaPrincipal parent;
    public List<Cliente> pesquisaCliente;
    
    

    /**
     * Creates new form PesquisarCliente
     */
    public PesquisaCliente(TelaPrincipal parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonPesquisar = new javax.swing.JButton();
        fCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        fSobrenome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesquisaCliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        pesquisaDetalhada = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel5.setText("jLabel5");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jLabel1.setText("Nome");

        fNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNomeKeyTyped(evt);
            }
        });

        jLabel3.setText("CPF");

        buttonPesquisar.setText("Pesquisar");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });

        try {
            fCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fCpfKeyTyped(evt);
            }
        });

        jLabel6.setText("Sobrenome");

        fSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fSobrenomeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fNome)
                            .addComponent(fCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(buttonPesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(fSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPesquisar))
        );

        fNome.setTransferHandler(null);
        fCpf.setTransferHandler(null);
        fSobrenome.setTransferHandler(null);

        tablePesquisaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Sobrenome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePesquisaCliente.getColumnModel().getColumn(0).setMinWidth(0);         tablePesquisaCliente.getColumnModel().getColumn(0).setMaxWidth(0);         tablePesquisaCliente.getColumnModel().getColumn(0).setWidth(0);
        tablePesquisaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesquisaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePesquisaCliente);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pesquisa Cliente");

        pesquisaDetalhada.setText("Detalhes do Cliente");
        pesquisaDetalhada.setEnabled(false);
        pesquisaDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaDetalhadaActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(pesquisaDetalhada)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisaDetalhada)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisaDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaDetalhadaActionPerformed
        try{
            int id = pesquisaCliente.get(tablePesquisaCliente.getSelectedRow()).getId();
            if(id >= 0){
                for(Cliente cliente : DaoCliente.listar()){
                    if(tablePesquisaCliente.getValueAt(tablePesquisaCliente.getSelectedRow() , 0) == cliente.getId()){
                        parent.abrirTelaDetalhesCliente(cliente);
                        DefaultTableModel model = (DefaultTableModel) tablePesquisaCliente.getModel();
                        model.setRowCount(0);
                        pesquisaDetalhada.setEnabled(false);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione 1 item para exibir detalhes");
            }  
        } catch (Exception e){
        }
    }//GEN-LAST:event_pesquisaDetalhadaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Deseja cancelar a pesquisa?") == 0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed
        pesquisaCliente = null;
        
        DefaultTableModel model = (DefaultTableModel) tablePesquisaCliente.getModel();
        model.setRowCount(0);
        
        try{
        pesquisaCliente = DaoCliente.procurarCliente(fNome.getText(), fSobrenome.getText()
                , fCpf.getText());
        } catch (Exception e){
            
        }
        
        if(pesquisaCliente == null){
            JOptionPane.showMessageDialog(this, "Nenhum resultado obtido");
        } else {
            for(int i = 0; i < pesquisaCliente.size(); i++){
                Cliente cliente = pesquisaCliente.get(i);
                if(cliente != null){
                    Object[] row = new Object[4];
                    row[0] = cliente.getId();
                    row[1] = cliente.getNome();
                    row[2] = cliente.getSobrenome();
                    row[3] = cliente.getCpf();
                    model.addRow(row);
                }
            }
        }
        pesquisaDetalhada.setEnabled(false);
    }//GEN-LAST:event_buttonPesquisarActionPerformed

    private void fCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fCpfKeyTyped
        Character ch = evt.getKeyChar();
        String permitidos = "0123456789";
        if(!permitidos.contains(ch.toString())){
            evt.consume();
        }
        
        if(fCpf.getText().length() == 11){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 11 Numeros");
        }
    }//GEN-LAST:event_fCpfKeyTyped

    private void fNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNomeKeyTyped
        String permitidos = "abcdefghijklmnopqrstuwyvxz".toUpperCase();
        Character ch = evt.getKeyChar();
        if(!permitidos.contains(ch.toString().toUpperCase())){
            evt.consume();
        }
        
        if(fNome.getText().length() == 20){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 20 Caracteres");
        }
    }//GEN-LAST:event_fNomeKeyTyped

    private void fSobrenomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSobrenomeKeyTyped
        String permitidos = " abcdefghijklmnopqrstuwyvxz".toUpperCase();
        Character ch = evt.getKeyChar();
        if(!permitidos.contains(ch.toString().toUpperCase())){
            evt.consume();
        }
        
        if(fNome.getText().length() == 50){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Maximo 50 Caracteres");
        }
    }//GEN-LAST:event_fSobrenomeKeyTyped

    private void tablePesquisaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesquisaClienteMouseClicked
        pesquisaDetalhada.setEnabled(true);
    }//GEN-LAST:event_tablePesquisaClienteMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JFormattedTextField fCpf;
    private javax.swing.JTextField fNome;
    private javax.swing.JTextField fSobrenome;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton pesquisaDetalhada;
    private javax.swing.JTable tablePesquisaCliente;
    // End of variables declaration//GEN-END:variables
}
